name: Android CI

on: [pull_request, push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Android SDK
      uses: amyu/setup-android@v1.1
      with:
        is-use-cache: true
        sdk-version: '27'
        build-tools-version: '31.0.0'
        cmake-version: '3.10.2.4988404'
        ndk-version: '23.1.7779620'
    - name: Setup Android SDK
      uses: amyu/setup-android@v1.1
      with:
        is-use-cache: true
        sdk-version: '28'
        build-tools-version: '28.0.3'
        cmake-version: '3.10.2.4988404'
        ndk-version: '23.1.7779620'
    - name: Setup Android SDK
      uses: amyu/setup-android@v1.1
      with:
        is-use-cache: true
        sdk-version: '31'
        build-tools-version: '31.0.0'
        cmake-version: '3.10.2.4988404'
        ndk-version: '23.1.7779620'
    - name: Build with Gradle
      run: cd VirtualApp && ./gradlew assembleRelease
    - name: ls
      run: ls
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with:
        name: compiled
        path: VirtualApp/app/build/
